# Generated by Django 5.0.1 on 2024-01-03 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0002_alter_marca_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stock_producto', models.SmallIntegerField()),
                ('id_marca_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.marca')),
            ],
            options={
                'db_table': 'cat_productos',
            },
        ),
    ]
